// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rbactest/v1/svc.proto

package rbactestv1

import (
	_ "github.com/toeydevelopment/protocas/proto/rbac/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_rbactest_v1_svc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rbactest_v1_svc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rbactest_v1_svc_proto_rawDescGZIP(), []int{0}
}

var File_rbactest_v1_svc_proto protoreflect.FileDescriptor

const file_rbactest_v1_svc_proto_rawDesc = "" +
	"\n" +
	"\x15rbactest/v1/svc.proto\x12\vrbactest.v1\x1a\x12rbac/v1/rbac.proto\"\a\n" +
	"\x05Empty2\xf2\x01\n" +
	"\x03Svc\x12H\n" +
	"\aGuarded\x12\x12.rbactest.v1.Empty\x1a\x12.rbactest.v1.Empty\"\x15\xda\xde\x1b\x11\n" +
	"\tfinancial\x12\x04view\x126\n" +
	"\x06Public\x12\x12.rbactest.v1.Empty\x1a\x12.rbactest.v1.Empty\"\x04\xe0\xde\x1b\x01\x120\n" +
	"\x04Bare\x12\x12.rbactest.v1.Empty\x1a\x12.rbactest.v1.Empty\"\x00\x127\n" +
	"\aInvalid\x12\x12.rbactest.v1.Empty\x1a\x12.rbactest.v1.Empty\"\x04\xda\xde\x1b\x00BTZRgithub.com/toeydevelopment/protocas/internal/testdata/proto/rbactest/v1;rbactestv1b\x06proto3"

var (
	file_rbactest_v1_svc_proto_rawDescOnce sync.Once
	file_rbactest_v1_svc_proto_rawDescData []byte
)

func file_rbactest_v1_svc_proto_rawDescGZIP() []byte {
	file_rbactest_v1_svc_proto_rawDescOnce.Do(func() {
		file_rbactest_v1_svc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rbactest_v1_svc_proto_rawDesc), len(file_rbactest_v1_svc_proto_rawDesc)))
	})
	return file_rbactest_v1_svc_proto_rawDescData
}

var file_rbactest_v1_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rbactest_v1_svc_proto_goTypes = []any{
	(*Empty)(nil), // 0: rbactest.v1.Empty
}
var file_rbactest_v1_svc_proto_depIdxs = []int32{
	0, // 0: rbactest.v1.Svc.Guarded:input_type -> rbactest.v1.Empty
	0, // 1: rbactest.v1.Svc.Public:input_type -> rbactest.v1.Empty
	0, // 2: rbactest.v1.Svc.Bare:input_type -> rbactest.v1.Empty
	0, // 3: rbactest.v1.Svc.Invalid:input_type -> rbactest.v1.Empty
	0, // 4: rbactest.v1.Svc.Guarded:output_type -> rbactest.v1.Empty
	0, // 5: rbactest.v1.Svc.Public:output_type -> rbactest.v1.Empty
	0, // 6: rbactest.v1.Svc.Bare:output_type -> rbactest.v1.Empty
	0, // 7: rbactest.v1.Svc.Invalid:output_type -> rbactest.v1.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rbactest_v1_svc_proto_init() }
func file_rbactest_v1_svc_proto_init() {
	if File_rbactest_v1_svc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rbactest_v1_svc_proto_rawDesc), len(file_rbactest_v1_svc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rbactest_v1_svc_proto_goTypes,
		DependencyIndexes: file_rbactest_v1_svc_proto_depIdxs,
		MessageInfos:      file_rbactest_v1_svc_proto_msgTypes,
	}.Build()
	File_rbactest_v1_svc_proto = out.File
	file_rbactest_v1_svc_proto_goTypes = nil
	file_rbactest_v1_svc_proto_depIdxs = nil
}
