// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rbac/v1/rbac.proto

package rbacv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Requirement is the permission an RPC needs.
type Requirement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"` // e.g. "financial", "inventory"
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`     // e.g. "view", "add", "edit", "delete"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Requirement) Reset() {
	*x = Requirement{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Requirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Requirement) ProtoMessage() {}

func (x *Requirement) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Requirement.ProtoReflect.Descriptor instead.
func (*Requirement) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{0}
}

func (x *Requirement) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Requirement) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

var file_rbac_v1_rbac_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Requirement)(nil),
		Field:         56811,
		Name:          "rbac.v1.require",
		Tag:           "bytes,56811,opt,name=require",
		Filename:      "rbac/v1/rbac.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         56812,
		Name:          "rbac.v1.skip",
		Tag:           "varint,56812,opt,name=skip",
		Filename:      "rbac/v1/rbac.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// require declares the permission this RPC needs.
	//
	// optional rbac.v1.Requirement require = 56811;
	E_Require = &file_rbac_v1_rbac_proto_extTypes[0]
	// skip marks the RPC as public / authorized elsewhere.
	//
	// optional bool skip = 56812;
	E_Skip = &file_rbac_v1_rbac_proto_extTypes[1]
)

var File_rbac_v1_rbac_proto protoreflect.FileDescriptor

const file_rbac_v1_rbac_proto_rawDesc = "" +
	"\n" +
	"\x12rbac/v1/rbac.proto\x12\arbac.v1\x1a google/protobuf/descriptor.proto\"A\n" +
	"\vRequirement\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action:P\n" +
	"\arequire\x12\x1e.google.protobuf.MethodOptions\x18\xeb\xbb\x03 \x01(\v2\x14.rbac.v1.RequirementR\arequire:4\n" +
	"\x04skip\x12\x1e.google.protobuf.MethodOptions\x18\xec\xbb\x03 \x01(\bR\x04skipB:Z8github.com/toeydevelopment/protocas/proto/rbac/v1;rbacv1b\x06proto3"

var (
	file_rbac_v1_rbac_proto_rawDescOnce sync.Once
	file_rbac_v1_rbac_proto_rawDescData []byte
)

func file_rbac_v1_rbac_proto_rawDescGZIP() []byte {
	file_rbac_v1_rbac_proto_rawDescOnce.Do(func() {
		file_rbac_v1_rbac_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rbac_v1_rbac_proto_rawDesc), len(file_rbac_v1_rbac_proto_rawDesc)))
	})
	return file_rbac_v1_rbac_proto_rawDescData
}

var file_rbac_v1_rbac_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rbac_v1_rbac_proto_goTypes = []any{
	(*Requirement)(nil),                // 0: rbac.v1.Requirement
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_rbac_v1_rbac_proto_depIdxs = []int32{
	1, // 0: rbac.v1.require:extendee -> google.protobuf.MethodOptions
	1, // 1: rbac.v1.skip:extendee -> google.protobuf.MethodOptions
	0, // 2: rbac.v1.require:type_name -> rbac.v1.Requirement
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rbac_v1_rbac_proto_init() }
func file_rbac_v1_rbac_proto_init() {
	if File_rbac_v1_rbac_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rbac_v1_rbac_proto_rawDesc), len(file_rbac_v1_rbac_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_rbac_v1_rbac_proto_goTypes,
		DependencyIndexes: file_rbac_v1_rbac_proto_depIdxs,
		MessageInfos:      file_rbac_v1_rbac_proto_msgTypes,
		ExtensionInfos:    file_rbac_v1_rbac_proto_extTypes,
	}.Build()
	File_rbac_v1_rbac_proto = out.File
	file_rbac_v1_rbac_proto_goTypes = nil
	file_rbac_v1_rbac_proto_depIdxs = nil
}
